services:
  db:
    image: postgres
    container_name: games_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
    volumes:
      - ./db/pgdata:/data/postgres
      - ./db/init:/docker-entrypoint-initdb.d

  games_api:
    container_name: games_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./:/api
    links:
      - 'db:db'
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
